# Generated by Django 6.0.2 on 2026-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userinfo_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
