# Generated by Django 6.0.2 on 2026-03-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='count',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
